name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.0
  - scikit-learn=0.24.2
  - matplotlib==3.6.3
  - plotly==5.13.0
  - pillow=9.4.0
  - mlflow=2.1.1
  - pip:
      - wandb==0.13.9
      - omegaconf==2.3.0