name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.28.2
  - pip=23.0
  - mlflow=2.1.1
  - hydra-core=1.3.1
  - pip:
      - wandb==0.13.9
      - hydra-joblib-launcher==1.2.0
